# Generated by Django 5.2.7 on 2025-11-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_selling_price_userfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(),
        ),
    ]
